
project_id = "eihzjfanyqdzeiitslyd"

[functions.property-insights]
verify_jwt = false

[auth.external.google]
enabled = true
client_id = "${GOOGLE_CLIENT_ID}"
secret = "${GOOGLE_CLIENT_SECRET}"
# Add the required configuration for Google auth redirect
additional_redirect_urls = ["https://eihzjfanyqdzeiitslyd.supabase.co/auth/v1/callback"]
