
project_id = "xudrepoheooqwymnsduu"

[functions.property-insights]
verify_jwt = false

[functions.get-api-tokens]
verify_jwt = true

[auth.external.google]
enabled = true
client_id = "${GOOGLE_CLIENT_ID}"
secret = "${GOOGLE_CLIENT_SECRET}"
# Add the required configuration for Google auth redirect
additional_redirect_urls = ["https://xudrepoheooqwymnsduu.supabase.co/auth/v1/callback", "https://tiptop-income-hub.lovable.app/dashboard"]

