// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eihzjfanyqdzeiitslyd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVpaHpqZmFueXFkemVpaXRzbHlkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwNzQ2NTMsImV4cCI6MjA2MDY1MDY1M30.JDDP3z2BsT3T7asrFlQr9HaROwOROi765TXXObGqwoI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);